-- AlterTable
ALTER TABLE "Store" ADD COLUMN "aceptaEfectivo" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "aceptaTransferencia" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "aceptaTarjeta" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "aceptaDelivery" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "aceptaRetiro" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Store" ADD COLUMN "aceptaMesa" BOOLEAN NOT NULL DEFAULT true;
