// GENERADO por pruebas/sifen/generar-esquema.ps1 a partir de los XSD oficiales de la DNIT
// (https://ekuatia.set.gov.py/sifen/xsd/ - DE_v150.xsd, DE_Types_v150.xsd, Unidades_Medida, Paises, Departamentos, Monedas).
// NO EDITAR A MANO: si la DNIT publica una version nueva, se bajan los XSD a pruebas/sifen/xsd y se vuelve a generar.

export type ElementoXsd = { n: string; t: string; min: number; max: number };
export type SimpleXsd = {
  base?: string; enum?: string[]; pat?: string[]; len?: number; minLen?: number; maxLen?: number;
  total?: number; frac?: number; minInc?: number | string; maxInc?: number | string; minExc?: number | string; maxExc?: number | string; union?: SimpleXsd[];
};
export type ComplejoXsd = { el: ElementoXsd[]; attr?: { n: string; t: string; req: boolean }[] };

export const RAIZ_DE = "rDE";

export const COMPLEJOS: Record<string, ComplejoXsd> = {
  "tgCOpeDE": {"el":[{"n":"iTipEmi","t":"tiTipEmi","min":1,"max":1},{"n":"dDesTipEmi","t":"tdDesTipEmi","min":1,"max":1},{"n":"dCodSeg","t":"tiCodSe","min":1,"max":1},{"n":"dInfoEmi","t":"tdInfoEmi","min":0,"max":1},{"n":"dInfoFisc","t":"tdInfoFisc","min":0,"max":1}]},
  "tgDTim": {"el":[{"n":"iTiDE","t":"tiTiDE","min":1,"max":1},{"n":"dDesTiDE","t":"tdDesTiDE","min":1,"max":1},{"n":"dNumTim","t":"tdNumTim","min":1,"max":1},{"n":"dEst","t":"tdEst","min":1,"max":1},{"n":"dPunExp","t":"tdPunExp","min":1,"max":1},{"n":"dNumDoc","t":"tdNumDoc","min":1,"max":1},{"n":"dSerieNum","t":"tdSerieNum","min":0,"max":1},{"n":"dFeIniT","t":"tdFeIniT","min":1,"max":1}]},
  "tgEmis": {"el":[{"n":"dRucEm","t":"tRuc","min":1,"max":1},{"n":"dDVEmi","t":"tDVer","min":1,"max":1},{"n":"iTipCont","t":"tiTipCont","min":1,"max":1},{"n":"cTipReg","t":"tcTipReg","min":0,"max":1},{"n":"dNomEmi","t":"tdNombre","min":1,"max":1},{"n":"dNomFanEmi","t":"tdNombre","min":0,"max":1},{"n":"dDirEmi","t":"tdDirec","min":1,"max":1},{"n":"dNumCas","t":"tdNumCas","min":1,"max":1},{"n":"dCompDir1","t":"tdDirec","min":0,"max":1},{"n":"dCompDir2","t":"tdDirec","min":0,"max":1},{"n":"cDepEmi","t":"tDepartamentos","min":1,"max":1},{"n":"dDesDepEmi","t":"tDesDepartamento","min":1,"max":1},{"n":"cDisEmi","t":"tcDisEmi","min":0,"max":1},{"n":"dDesDisEmi","t":"tdDesDisEmi","min":0,"max":1},{"n":"cCiuEmi","t":"tcCiuEmi","min":1,"max":1},{"n":"dDesCiuEmi","t":"tdDesCiuEmi","min":1,"max":1},{"n":"dTelEmi","t":"tdTel","min":1,"max":1},{"n":"dEmailE","t":"tEmail","min":1,"max":1},{"n":"dDenSuc","t":"tgEmis.dDenSuc","min":0,"max":1},{"n":"gActEco","t":"tgActEco","min":1,"max":9},{"n":"gRespDE","t":"tgRespDE","min":0,"max":1}]},
  "tgActEco": {"el":[{"n":"cActEco","t":"tcActEco","min":1,"max":1},{"n":"dDesActEco","t":"tdDesActEco","min":1,"max":1}]},
  "tgRespDE": {"el":[{"n":"iTipIDRespDE","t":"tiTipIDRespDE","min":1,"max":1},{"n":"dDTipIDRespDE","t":"tdDTipIDRespDE","min":1,"max":1},{"n":"dNumIDRespDE","t":"tdNumDocId","min":1,"max":1},{"n":"dNomRespDE","t":"tdNombre","min":1,"max":1},{"n":"dCarRespDE","t":"tdCargo","min":1,"max":1}]},
  "tgDatRec": {"el":[{"n":"iNatRec","t":"tiNatRec","min":1,"max":1},{"n":"iTiOpe","t":"tiTiOpe","min":1,"max":1},{"n":"cPaisRec","t":"paisType","min":1,"max":1},{"n":"dDesPaisRe","t":"tDesPais","min":1,"max":1},{"n":"iTiContRec","t":"tiTipCont","min":0,"max":1},{"n":"dRucRec","t":"tRuc","min":0,"max":1},{"n":"dDVRec","t":"tDVer","min":0,"max":1},{"n":"iTipIDRec","t":"tiTipDocRec","min":0,"max":1},{"n":"dDTipIDRec","t":"tdDtipDocRec","min":0,"max":1},{"n":"dNumIDRec","t":"tdNumDocId","min":0,"max":1},{"n":"dNomRec","t":"tdNombre","min":1,"max":1},{"n":"dNomFanRec","t":"tdNombre","min":0,"max":1},{"n":"dDirRec","t":"tdDirec","min":0,"max":1},{"n":"dNumCasRec","t":"tdNumCas","min":0,"max":1},{"n":"cDepRec","t":"tDepartamentos","min":0,"max":1},{"n":"dDesDepRec","t":"tDesDepartamento","min":0,"max":1},{"n":"cDisRec","t":"tDistrito","min":0,"max":1},{"n":"dDesDisRec","t":"tDesDistrito","min":0,"max":1},{"n":"cCiuRec","t":"tCiudad","min":0,"max":1},{"n":"dDesCiuRec","t":"tDesCiudad","min":0,"max":1},{"n":"dTelRec","t":"tdTel","min":0,"max":1},{"n":"dCelRec","t":"tdCel","min":0,"max":1},{"n":"dEmailRec","t":"tEmail","min":0,"max":1},{"n":"dCodCliente","t":"tgDatRec.dCodCliente","min":0,"max":1}]},
  "tgDaGOC": {"el":[{"n":"dFeEmiDE","t":"fecHhmmss","min":1,"max":1},{"n":"gOpeCom","t":"tgOpeCom","min":0,"max":1},{"n":"gEmis","t":"tgEmis","min":1,"max":1},{"n":"gDatRec","t":"tgDatRec","min":1,"max":1}]},
  "tgOpeCom": {"el":[{"n":"iTipTra","t":"tiTipTra","min":0,"max":1},{"n":"dDesTipTra","t":"tdDesTiTran","min":0,"max":1},{"n":"iTImp","t":"tiTImp","min":1,"max":1},{"n":"dDesTImp","t":"tdDesTImp","min":1,"max":1},{"n":"cMoneOpe","t":"cMondT","min":1,"max":1},{"n":"dDesMoneOpe","t":"tdDMoneTiPag","min":1,"max":1},{"n":"dCondTiCam","t":"tdCondTiCam","min":0,"max":1},{"n":"dTiCam","t":"tTipoCambioBase","min":0,"max":1},{"n":"iCondAnt","t":"tiCondAnt","min":0,"max":1},{"n":"dDesCondAnt","t":"tdDesCondAnt","min":0,"max":1},{"n":"gOblAfe","t":"tgOblAfe","min":0,"max":12}]},
  "tgOblAfe": {"el":[{"n":"cOblAfe","t":"tcOblAfe","min":1,"max":1},{"n":"dDesOblAfe","t":"tdDesOblAfe","min":1,"max":1}]},
  "tgPagTarCD": {"el":[{"n":"iDenTarj","t":"tiDenTarj","min":1,"max":1},{"n":"dDesDenTarj","t":"tdDesDenTarj","min":1,"max":1},{"n":"dRSProTar","t":"dNomRazSocial","min":0,"max":1},{"n":"dRUCProTar","t":"tRuc","min":0,"max":1},{"n":"dDVProTar","t":"tDVer","min":0,"max":1},{"n":"iForProPa","t":"tiForProPa","min":1,"max":1},{"n":"dCodAuOpe","t":"tdNunApOpe","min":0,"max":1},{"n":"dNomTit","t":"tgPagTarCD.dNomTit","min":0,"max":1},{"n":"dNumTarj","t":"tgPagTarCD.dNumTarj","min":0,"max":1}]},
  "tgPagCheq": {"el":[{"n":"dNumCheq","t":"tNumCheq","min":1,"max":1},{"n":"dBcoEmi","t":"tgPagCheq.dBcoEmi","min":1,"max":1}]},
  "tgCuotas": {"el":[{"n":"cMoneCuo","t":"cMondT","min":1,"max":1},{"n":"dDMoneCuo","t":"tdDMoneTiPag","min":1,"max":1},{"n":"dMonCuota","t":"tMontoBase4","min":1,"max":1},{"n":"dVencCuo","t":"tFecAAAAMMDDguion","min":0,"max":1}]},
  "tgCompPub": {"el":[{"n":"dModCont","t":"tdModCont","min":1,"max":1},{"n":"dEntCont ","t":"tdEntCont","min":1,"max":1},{"n":"dAnoCont","t":"tdAnoCont","min":1,"max":1},{"n":"dSecCont","t":"tdSecCont","min":1,"max":1},{"n":"dFeCodCont","t":"tFecAAAAMMDDguion","min":1,"max":1}]},
  "tgCamFE": {"el":[{"n":"iIndPres","t":"tiIndPres","min":1,"max":1},{"n":"dDesIndPres","t":"tdDesIndPres","min":1,"max":1},{"n":"dFecEmNR","t":"tFecAAAAMMDDguion","min":0,"max":1},{"n":"gCompPub","t":"tgCompPub","min":0,"max":1}]},
  "tgValorItem": {"el":[{"n":"dPUniProSer","t":"tMontoBase","min":1,"max":1},{"n":"dTiCamIt","t":"tTipoCambioBase","min":0,"max":1},{"n":"dTotBruOpeItem","t":"tMontoBase","min":1,"max":1},{"n":"gValorRestaItem","t":"tgValorRestaItem","min":1,"max":1}]},
  "tgValorRestaItem": {"el":[{"n":"dDescItem","t":"tMontoBase","min":0,"max":1},{"n":"dPorcDesIt","t":"tPorcDesc8","min":0,"max":1},{"n":"dDescGloItem","t":"tMontoBase","min":0,"max":1},{"n":"dAntPreUniIt","t":"tMontoBase","min":0,"max":1},{"n":"dAntGloPreUniIt","t":"tMontoBase","min":0,"max":1},{"n":"dTotOpeItem","t":"tMontoBase","min":1,"max":1},{"n":"dTotOpeGs","t":"tMontoBase","min":0,"max":1}]},
  "tgCamIVA": {"el":[{"n":"iAfecIVA","t":"tiAfecIVA","min":1,"max":1},{"n":"dDesAfecIVA","t":"tdDesAfecIVA","min":1,"max":1},{"n":"dPropIVA","t":"tPorcDesc8","min":1,"max":1},{"n":"dTasaIVA","t":"tdTasaIVA","min":1,"max":1},{"n":"dBasGravIVA","t":"tMontoBase","min":1,"max":1},{"n":"dLiqIVAItem","t":"tMontoBase","min":1,"max":1},{"n":"dBasExe","t":"tMontoBase","min":1,"max":1}]},
  "tgCamISC": {"el":[{"n":"cCatISC","t":"tcCatISC","min":1,"max":1},{"n":"dDesCatISC","t":"tdDesCatISC","min":1,"max":1},{"n":"cTasaISC","t":"tcTasaISC","min":1,"max":1},{"n":"dBaseGravISC","t":"tMontoBase","min":1,"max":1},{"n":"dLiqISCItem","t":"tMontoBase","min":1,"max":1}]},
  "tgRasMerc": {"el":[{"n":"dNumLote","t":"tgRasMerc.dNumLote","min":0,"max":1},{"n":"dVencMerc","t":"tFecAAAAMMDDguion","min":0,"max":1},{"n":"dNSerie","t":"tgRasMerc.dNSerie","min":0,"max":1},{"n":"dNumPedi","t":"tgRasMerc.dNumPedi","min":0,"max":1},{"n":"dNumSegui","t":"tgRasMerc.dNumSegui","min":0,"max":1},{"n":"dNumReg","t":"tdCadenaBase20","min":0,"max":1},{"n":"dNumRegEntCom","t":"tdCadenaBase20","min":0,"max":1},{"n":"dNomPro","t":"tdNomPro","min":0,"max":1}]},
  "tgVehNuevo": {"el":[{"n":"iTipOpVN","t":"tiTipOpVN","min":0,"max":1},{"n":"dDesTipOpVN","t":"tdDesTipOpVN","min":0,"max":1},{"n":"dChasis","t":"tdChasis","min":0,"max":1},{"n":"dColor","t":"tgVehNuevo.dColor","min":0,"max":1},{"n":"dPotencia","t":"tgVehNuevo.dPotencia","min":0,"max":1},{"n":"dCapMot","t":"tgVehNuevo.dCapMot","min":0,"max":1},{"n":"dPNet","t":"tMontoBase6","min":0,"max":1},{"n":"dPBruto","t":"tMontoBase6","min":0,"max":1},{"n":"iTipCom","t":"tiTipCom","min":0,"max":1},{"n":"dDesTipCom","t":"tdDesTipCom","min":0,"max":1},{"n":"dNroMotor","t":"tgVehNuevo.dNroMotor","min":0,"max":1},{"n":"dCapTracc","t":"tMontoBase6","min":0,"max":1},{"n":"dAnoFab","t":"tgVehNuevo.dAnoFab","min":0,"max":1},{"n":"cTipVeh","t":"tcTipVeh","min":0,"max":1},{"n":"dCapac","t":"tgVehNuevo.dCapac","min":0,"max":1},{"n":"dCilin","t":"tgVehNuevo.dCilin","min":0,"max":1}]},
  "tgGrupEner": {"el":[{"n":"dNroMed","t":"tgGrupEner.dNroMed","min":0,"max":1},{"n":"dActiv","t":"tgGrupEner.dActiv","min":0,"max":1},{"n":"dCateg","t":"tgGrupEner.dCateg","min":0,"max":1},{"n":"dLecAnt","t":"tLectura","min":0,"max":1},{"n":"dLecAct","t":"tLectura","min":0,"max":1},{"n":"dConKwh","t":"tLectura","min":0,"max":1}]},
  "tgGrupSup": {"el":[{"n":"dNomCaj","t":"tgGrupSup.dNomCaj","min":0,"max":1},{"n":"dEfectivo","t":"tMontoBase4","min":0,"max":1},{"n":"dVuelto","t":"tMontoBase6","min":0,"max":1},{"n":"dDonac","t":"tMontoBase6","min":0,"max":1},{"n":"dDesDonac","t":"tgGrupSup.dDesDonac","min":0,"max":1}]},
  "tgGrupSeg": {"el":[{"n":"dCodEmpSeg","t":"tgGrupSeg.dCodEmpSeg","min":0,"max":1},{"n":"gGrupPolSeg","t":"tgGrupPolSeg","min":1,"max":999}]},
  "tgGrupPolSeg": {"el":[{"n":"dPoliza","t":"tdPoliza","min":1,"max":1},{"n":"dUnidVig","t":"tgGrupPolSeg.dUnidVig","min":1,"max":1},{"n":"dVigencia","t":"tdVigPol","min":1,"max":1},{"n":"dNumPoliza","t":"tgGrupPolSeg.dNumPoliza","min":1,"max":1},{"n":"dFecIniVig","t":"fecHhmmss","min":0,"max":1},{"n":"dFecFinVig","t":"fecHhmmss","min":0,"max":1},{"n":"dCodInt","t":"tgGrupPolSeg.dCodInt","min":0,"max":1}]},
  "tgCamEsp": {"el":[{"n":"gGrupEner","t":"tgGrupEner","min":0,"max":9},{"n":"gGrupSeg","t":"tgGrupSeg","min":0,"max":1},{"n":"gGrupSup","t":"tgGrupSup","min":0,"max":1},{"n":"gGrupAdi","t":"tgGrupAdi","min":0,"max":1}]},
  "tgGrupAdi": {"el":[{"n":"dCiclo","t":"tgGrupAdi.dCiclo","min":0,"max":1},{"n":"dFecIniC","t":"tdFeIniS","min":0,"max":1},{"n":"dFecFinC","t":"tFecAAAAMMDDguion","min":0,"max":1},{"n":"dVencPag","t":"tFecAAAAMMDDguion","min":0,"max":3},{"n":"dContrato","t":"tgGrupAdi.dContrato","min":0,"max":1},{"n":"dSalAnt","t":"tMontoBase4","min":0,"max":1},{"n":"dCodConDncp","t":"tgGrupAdi.dCodConDncp","min":0,"max":1}]},
  "tgCamItem": {"el":[{"n":"dCodInt","t":"tdCodInt","min":1,"max":1},{"n":"dParAranc","t":"tdParAranc","min":0,"max":1},{"n":"dNCM","t":"tdNCM","min":0,"max":1},{"n":"dDncpG","t":"tdDncpG","min":0,"max":1},{"n":"dDncpE","t":"tdDncpE","min":0,"max":1},{"n":"dGtin","t":"tdGtin","min":0,"max":1},{"n":"dGtinPq","t":"tdGtin","min":0,"max":1},{"n":"dDesProSer","t":"tgCamItem.dDesProSer","min":1,"max":1},{"n":"cUniMed","t":"tcUniMed","min":1,"max":1},{"n":"dDesUniMed","t":"tdDesUniMed","min":1,"max":1},{"n":"dCantProSer","t":"tdCantProSer","min":1,"max":1},{"n":"cPaisOrig","t":"paisType","min":0,"max":1},{"n":"dDesPaisOrig","t":"tDesPais","min":0,"max":1},{"n":"dInfItem","t":"tgCamItem.dInfItem","min":0,"max":1},{"n":"cRelMerc","t":"tcRelMerc","min":0,"max":1},{"n":"dDesRelMerc","t":"tdDesRelMerc","min":0,"max":1},{"n":"dCanQuiMer","t":"tgCamItem.dCanQuiMer","min":0,"max":1},{"n":"dPorQuiMer","t":"tPorcDesc8","min":0,"max":1},{"n":"dCDCAnticipo","t":"tCDC","min":0,"max":1},{"n":"gValorItem","t":"tgValorItem","min":0,"max":1},{"n":"gCamIVA","t":"tgCamIVA","min":0,"max":1},{"n":"gRasMerc","t":"tgRasMerc","min":0,"max":1},{"n":"gVehNuevo","t":"tgVehNuevo","min":0,"max":1}]},
  "tgDtipDE": {"el":[{"n":"gCamFE","t":"tgCamFE","min":0,"max":1},{"n":"gCamAE","t":"tgCamAE","min":0,"max":1},{"n":"gCamNCDE","t":"tgCamNCDE","min":0,"max":1},{"n":"gCamNRE","t":"tgCamNRE","min":0,"max":1},{"n":"gCamCond","t":"tgCamCond","min":0,"max":1},{"n":"gCamItem","t":"tgCamItem","min":1,"max":999},{"n":"gCamEsp","t":"tgCamEsp","min":0,"max":1},{"n":"gTransp","t":"tgTransp","min":0,"max":1},{"n":"gCamRDE","t":"tgCamRDE","min":0,"max":999}]},
  "tgCamTrans": {"el":[{"n":"iNatTrans","t":"tiNatRec","min":1,"max":1},{"n":"dNomTrans","t":"dNomRazSocial","min":1,"max":1},{"n":"dRucTrans","t":"tRuc","min":0,"max":1},{"n":"dDVTrans","t":"tDVer","min":0,"max":1},{"n":"iTipIDTrans","t":"tiTipDoc","min":0,"max":1},{"n":"dDTipIDTrans","t":"tdDtipDoc","min":0,"max":1},{"n":"dNumIDTrans","t":"tdNumDocId","min":0,"max":1},{"n":"cNacTrans","t":"paisType","min":0,"max":1},{"n":"dDesNacTrans","t":"tDesPais","min":0,"max":1},{"n":"dNumIDChof","t":"tdNumDocId","min":1,"max":1},{"n":"dNomChof","t":"dNomRazSocial","min":1,"max":1},{"n":"dDomFisc","t":"tgCamTrans.dDomFisc","min":1,"max":1},{"n":"dDirChof","t":"tdDirec","min":1,"max":1},{"n":"dNombAg","t":"dNomRazSocial","min":0,"max":1},{"n":"dRucAg","t":"tRuc","min":0,"max":1},{"n":"dDVAg","t":"tDVer","min":0,"max":1},{"n":"dDirAge","t":"tdDirec","min":0,"max":1}]},
  "tgCamNCDE": {"el":[{"n":"iMotEmi","t":"tiMotEmi","min":1,"max":1},{"n":"dDesMotEmi","t":"tdDesMotEmi","min":1,"max":1}]},
  "tgCamNRE": {"el":[{"n":"iMotEmiNR","t":"tiMotivTras","min":1,"max":1},{"n":"dDesMotEmiNR","t":"tdDMotivTras","min":1,"max":1},{"n":"iRespEmiNR","t":"tiRespEmiNR","min":1,"max":1},{"n":"dDesRespEmiNR","t":"tdDesRespEmiNR","min":1,"max":1},{"n":"dKmR","t":"tgCamNRE.dKmR","min":1,"max":1},{"n":"dFecEm","t":"tFecAAAAMMDDguion","min":0,"max":1},{"n":"cPreFle","t":"tMontoBase","min":0,"max":1}]},
  "tgTransp": {"el":[{"n":"iTipTrans","t":"tiTTrans","min":0,"max":1},{"n":"dDesTipTrans","t":"tdDesTTrans","min":0,"max":1},{"n":"iModTrans","t":"tiModTrans","min":1,"max":1},{"n":"dDesModTrans","t":"tdDesModTrans","min":1,"max":1},{"n":"iRespFlete","t":"tiRespFlete","min":1,"max":1},{"n":"cCondNeg","t":"tcCondNeg","min":0,"max":1},{"n":"dNuManif","t":"tgTransp.dNuManif","min":0,"max":1},{"n":"dNuDespImp","t":"tgTransp.dNuDespImp","min":0,"max":1},{"n":"dIniTras","t":"tdFeIniS","min":0,"max":1},{"n":"dFinTras","t":"tFecAAAAMMDDguion","min":0,"max":1},{"n":"cPaisDest","t":"paisType","min":0,"max":1},{"n":"dDesPaisDest","t":"tDesPais","min":0,"max":1},{"n":"gCamSal","t":"tgCamSal","min":0,"max":1},{"n":"gCamEnt","t":"tgCamEnt","min":0,"max":99},{"n":"gVehTras","t":"tgVehTras","min":0,"max":4},{"n":"gCamTrans","t":"tgCamTrans","min":0,"max":1}]},
  "tgVehTras": {"el":[{"n":"dTiVehTras","t":"tgVehTras.dTiVehTras","min":1,"max":1},{"n":"dMarVeh","t":"tgVehTras.dMarVeh","min":1,"max":1},{"n":"dTipIdenVeh","t":"tgVehTras.dTipIdenVeh","min":1,"max":1},{"n":"dNroIDVeh","t":"tgVehTras.dNroIDVeh","min":0,"max":1},{"n":"dAdicVeh","t":"tgVehTras.dAdicVeh","min":0,"max":1},{"n":"dNroMatVeh","t":"tgVehTras.dNroMatVeh","min":0,"max":1},{"n":"dNroVuelo","t":"tgVehTras.dNroVuelo","min":0,"max":1}]},
  "tgCamEnt": {"el":[{"n":"dDirLocEnt","t":"tdDirec","min":1,"max":1},{"n":"dNumCasEnt","t":"tdNumCas","min":1,"max":1},{"n":"dComp1Ent","t":"tdDirec","min":0,"max":1},{"n":"dComp2Ent","t":"tdDirec","min":0,"max":1},{"n":"cDepEnt","t":"tDepartamentos","min":1,"max":1},{"n":"dDesDepEnt","t":"tDesDepartamento","min":1,"max":1},{"n":"cDisEnt","t":"tDistrito","min":0,"max":1},{"n":"dDesDisEnt","t":"tDesDistrito","min":0,"max":1},{"n":"cCiuEnt","t":"tCiudad","min":1,"max":1},{"n":"dDesCiuEnt","t":"tDesCiudad","min":1,"max":1},{"n":"dTelEnt","t":"tdTel","min":0,"max":1}]},
  "tgCamSal": {"el":[{"n":"dDirLocSal","t":"tdDirec","min":1,"max":1},{"n":"dNumCasSal","t":"tdNumCas","min":1,"max":1},{"n":"dComp1Sal","t":"tdDirec","min":0,"max":1},{"n":"dComp2Sal","t":"tdDirec","min":0,"max":1},{"n":"cDepSal","t":"tDepartamentos","min":1,"max":1},{"n":"dDesDepSal","t":"tDesDepartamento","min":1,"max":1},{"n":"cDisSal","t":"tDistrito","min":0,"max":1},{"n":"dDesDisSal","t":"tDesDistrito","min":0,"max":1},{"n":"cCiuSal","t":"tCiudad","min":1,"max":1},{"n":"dDesCiuSal","t":"tDesCiudad","min":1,"max":1},{"n":"dTelSal","t":"tdTel","min":0,"max":1}]},
  "tgCamCond": {"el":[{"n":"iCondOpe","t":"tiCondOpe","min":1,"max":1},{"n":"dDCondOpe","t":"tdDCondOpe","min":1,"max":1},{"n":"gPaConEIni","t":"tgPagCont","min":0,"max":999},{"n":"gPagCred","t":"tgPagCred","min":0,"max":1}]},
  "tgPagCont": {"el":[{"n":"iTiPago","t":"tiTiPago","min":1,"max":1},{"n":"dDesTiPag","t":"tdDesTiPag","min":1,"max":1},{"n":"dMonTiPag","t":"tMontoBase4","min":1,"max":1},{"n":"cMoneTiPag","t":"cMondT","min":1,"max":1},{"n":"dDMoneTiPag","t":"tdDMoneTiPag","min":1,"max":1},{"n":"dTiCamTiPag","t":"tTipoCambioBase","min":0,"max":1},{"n":"gPagTarCD","t":"tgPagTarCD","min":0,"max":1},{"n":"gPagCheq","t":"tgPagCheq","min":0,"max":1}]},
  "tgPagCred": {"el":[{"n":"iCondCred","t":"tgPagCred.iCondCred","min":1,"max":1},{"n":"dDCondCred","t":"tdDCondCred","min":1,"max":1},{"n":"dPlazoCre","t":"tgPagCred.dPlazoCre","min":0,"max":1},{"n":"dCuotas","t":"tgPagCred.dCuotas","min":0,"max":1},{"n":"dMonEnt","t":"tMontoBase4","min":0,"max":1},{"n":"gCuotas","t":"tgCuotas","min":0,"max":999}]},
  "tgCamAE": {"el":[{"n":"iNatVen","t":"tiNatVen","min":1,"max":1},{"n":"dDesNatVen","t":"tdDesNatVen","min":1,"max":1},{"n":"iTipIDVen","t":"tiTipDoc","min":1,"max":1},{"n":"dDTipIDVen","t":"tdDtipDoc","min":1,"max":1},{"n":"dNumIDVen","t":"tdNumDocId","min":1,"max":1},{"n":"dNomVen","t":"dNomRazSocial","min":1,"max":1},{"n":"dDirVen","t":"tdDirec","min":1,"max":1},{"n":"dNumCasVen","t":"tdNumCas","min":1,"max":1},{"n":"cDepVen","t":"tDepartamentos","min":1,"max":1},{"n":"dDesDepVen","t":"tDesDepartamento","min":1,"max":1},{"n":"cDisVen","t":"tDistrito","min":0,"max":1},{"n":"dDesDisVen","t":"tDesDistrito","min":0,"max":1},{"n":"cCiuVen","t":"tCiudad","min":1,"max":1},{"n":"dDesCiuVen","t":"tDesCiudad","min":1,"max":1},{"n":"dDirProv","t":"tdDirec","min":1,"max":1},{"n":"cDepProv","t":"tDepartamentos","min":1,"max":1},{"n":"dDesDepProv","t":"tDesDepartamento","min":1,"max":1},{"n":"cDisProv","t":"tDistrito","min":0,"max":1},{"n":"dDesDisProv","t":"tDesDistrito","min":0,"max":1},{"n":"cCiuProv","t":"tCiudad","min":1,"max":1},{"n":"dDesCiuProv","t":"tDesCiudad","min":1,"max":1}]},
  "tgCamFEI": {"el":[{"n":"cTipRegImp","t":"tcTipRegAdu","min":1,"max":1},{"n":"dPuLleg","t":"tgCamFEI.dPuLleg","min":1,"max":1},{"n":"dNuDesp","t":"tgCamFEI.dNuDesp","min":1,"max":1},{"n":"dFecDesp","t":"tFecAAAAMMDDguion","min":1,"max":1},{"n":"dNomDesp","t":"tgCamFEI.dNomDesp","min":1,"max":1},{"n":"dRucDesp","t":"tRuc","min":1,"max":1},{"n":"dDVDesp","t":"tDVer","min":1,"max":1},{"n":"cPaisProd","t":"paisType","min":1,"max":1},{"n":"dDesPaisProd","t":"tDesPais","min":1,"max":1},{"n":"dVend","t":"tgCamFEI.dVend","min":1,"max":1},{"n":"dValorInv","t":"tgCamFEI.dValorInv","min":1,"max":1},{"n":"dValorFle","t":"tgCamFEI.dValorFle","min":1,"max":1},{"n":"dValorSeg","t":"tgCamFEI.dValorSeg","min":1,"max":1},{"n":"dValorImpGs","t":"tgCamFEI.dValorImpGs","min":1,"max":1},{"n":"dDerAdu","t":"tgCamFEI.dDerAdu","min":1,"max":1},{"n":"dIndi","t":"tgCamFEI.dIndi","min":1,"max":1},{"n":"dSerValor","t":"tgCamFEI.dSerValor","min":1,"max":1},{"n":"dIVAImp","t":"tgCamFEI.dIVAImp","min":1,"max":1},{"n":"dTasaIntAd","t":"tgCamFEI.dTasaIntAd","min":1,"max":1}]},
  "tgCamFEE": {"el":[{"n":"cFleExp","t":"paisType","min":1,"max":1},{"n":"dDesFleExp","t":"tDesPais","min":1,"max":1},{"n":"dPuEmb","t":"tgCamFEE.dPuEmb","min":1,"max":1}]},
  "tgTotSub": {"el":[{"n":"dSubExe","t":"tMontoBase","min":0,"max":1},{"n":"dSubExo","t":"tMontoBase","min":0,"max":1},{"n":"dSub5","t":"tMontoBase","min":0,"max":1},{"n":"dSub10","t":"tMontoBase","min":0,"max":1},{"n":"dTotOpe","t":"tMontoBase","min":1,"max":1},{"n":"dTotDesc","t":"tMontoBase","min":1,"max":1},{"n":"dTotDescGlotem","t":"tMontoBase","min":1,"max":1},{"n":"dTotAntItem","t":"tMontoBase","min":1,"max":1},{"n":"dTotAnt","t":"tMontoBase","min":1,"max":1},{"n":"dPorcDescTotal","t":"tPorcDesc8","min":1,"max":1},{"n":"dDescTotal","t":"tMontoBase","min":1,"max":1},{"n":"dAnticipo","t":"tMontoBase","min":1,"max":1},{"n":"dRedon","t":"tdCRed","min":1,"max":1},{"n":"dComi","t":"tMontoBase","min":0,"max":1},{"n":"dTotGralOpe","t":"tMontoBase","min":1,"max":1},{"n":"dIVA5","t":"tMontoBase","min":0,"max":1},{"n":"dIVA10","t":"tMontoBase","min":0,"max":1},{"n":"dLiqTotIVA5","t":"tMontoBase","min":0,"max":1},{"n":"dLiqTotIVA10","t":"tMontoBase","min":0,"max":1},{"n":"dIVAComi","t":"tMontoBase","min":0,"max":1},{"n":"dTotIVA","t":"tMontoBase","min":0,"max":1},{"n":"dBaseGrav5","t":"tMontoBase","min":0,"max":1},{"n":"dBaseGrav10","t":"tMontoBase","min":0,"max":1},{"n":"dTBasGraIVA","t":"tMontoBase","min":0,"max":1},{"n":"dTotalGs","t":"tMontoBase","min":0,"max":1}]},
  "tDE": {"el":[{"n":"dDVId","t":"tDVer","min":1,"max":1},{"n":"dFecFirma","t":"fecHhmmss","min":1,"max":1},{"n":"dSisFact","t":"tDE.dSisFact","min":1,"max":1},{"n":"gOpeDE","t":"tgCOpeDE","min":1,"max":1},{"n":"gTimb","t":"tgDTim","min":1,"max":1},{"n":"gDatGralOpe","t":"tgDaGOC","min":1,"max":1},{"n":"gDtipDE","t":"tgDtipDE","min":1,"max":1},{"n":"gTotSub","t":"tgTotSub","min":0,"max":1},{"n":"gCamGen","t":"tgCamGen","min":0,"max":1},{"n":"gCamDEAsoc","t":"tgCamDEAsoc","min":0,"max":99}],"attr":[{"n":"Id","t":"tCDC","req":true}]},
  "tgCamDEAsoc": {"el":[{"n":"iTipDocAso","t":"tiTipDocAso","min":1,"max":1},{"n":"dDesTipDocAso","t":"tdDesTipDocAso","min":1,"max":1},{"n":"dCdCDERef","t":"tCDC","min":0,"max":1},{"n":"dNTimDI","t":"tdNumTim","min":0,"max":1},{"n":"dEstDocAso","t":"tdEst","min":0,"max":1},{"n":"dPExpDocAso","t":"tdPunExp","min":0,"max":1},{"n":"dNumDocAso","t":"tdNumDoc","min":0,"max":1},{"n":"iTipoDocAso","t":"tiTIpoDoc","min":0,"max":1},{"n":"dDTipoDocAso","t":"tdDesTIpoDoc","min":0,"max":1},{"n":"dFecEmiDI","t":"tFecDocImpAAAAMMDDguion","min":0,"max":1},{"n":"dNumComRet","t":"tgCamDEAsoc.dNumComRet","min":0,"max":1},{"n":"dNumResCF","t":"tgCamDEAsoc.dNumResCF","min":0,"max":1},{"n":"iTipCons","t":"tdTipCons","min":0,"max":1},{"n":"dDesTipCons","t":"tdDesTipCons","min":0,"max":1},{"n":"dNumCons","t":"tgCamDEAsoc.dNumCons","min":0,"max":1},{"n":"dNumControl","t":"tgCamDEAsoc.dNumControl","min":0,"max":1},{"n":"dRucFus","t":"tRuc","min":0,"max":1},{"n":"dNumCuoDocAso","t":"xs:anyType","min":0,"max":1},{"n":"dImpCuoDocAso","t":"xs:anyType","min":0,"max":1}]},
  "tgCamGen": {"el":[{"n":"dOrdCompra","t":"tgCamGen.dOrdCompra","min":0,"max":1},{"n":"dOrdVta","t":"tgCamGen.dOrdVta","min":0,"max":1},{"n":"dAsiento","t":"tgCamGen.dAsiento","min":0,"max":1},{"n":"gCamCarg","t":"tgCamCarg","min":0,"max":1}]},
  "tgCamCarg": {"el":[{"n":"cUniMedTotVol","t":"tcUniMed","min":0,"max":1},{"n":"dDesUniMedTotVol","t":"tdDesUniMed","min":0,"max":1},{"n":"dTotVolMerc","t":"tgCamCarg.dTotVolMerc","min":0,"max":1},{"n":"cUniMedTotPes","t":"tcUniMed","min":0,"max":1},{"n":"dDesUniMedTotPes","t":"tdDesUniMed","min":0,"max":1},{"n":"dTotPesMerc","t":"tgCamCarg.dTotPesMerc","min":0,"max":1},{"n":"iCarCarga","t":"tgCamCarg.iCarCarga","min":0,"max":1},{"n":"dDesCarCarga","t":"tgCamCarg.dDesCarCarga","min":0,"max":1}]},
  "tgCamFuFD": {"el":[{"n":"dCarQR","t":"tgCamFuFD.dCarQR","min":1,"max":1},{"n":"dInfAdic","t":"tgCamFuFD.dInfAdic","min":0,"max":1}]},
  "rDE": {"el":[{"n":"dVerFor","t":"rDE.dVerFor","min":1,"max":1},{"n":"DE","t":"tDE","min":1,"max":1},{"n":"Signature","t":"ds:Signature","min":1,"max":1},{"n":"gCamFuFD","t":"tgCamFuFD","min":1,"max":1}]},
  "tgCamRDE": {"el":[{"n":"iForPag","t":"tiForPag","min":1,"max":1},{"n":"dDesForPag","t":"tdDesForPag","min":1,"max":1},{"n":"dNumTrans","t":"tgCamRDE.dNumTrans","min":0,"max":1},{"n":"dConc","t":"tgCamRDE.dConc","min":1,"max":1},{"n":"dRucEntFin","t":"tRuc","min":0,"max":1},{"n":"dDvEntFin","t":"tDVer","min":0,"max":1},{"n":"dNomEntFin","t":"tgCamRDE.dNomEntFin","min":0,"max":1},{"n":"dImpPag","t":"tMontoBase4","min":1,"max":1}]},
};

export const SIMPLES: Record<string, SimpleXsd> = {
  "tgEmis.dDenSuc": {"base":"noEmptyString","maxLen":30,"minLen":1},
  "tgDatRec.dCodCliente": {"base":"xs:string","minLen":3,"maxLen":15},
  "tgPagTarCD.dNomTit": {"base":"noEmptyString","minLen":4,"maxLen":30},
  "tgPagTarCD.dNumTarj": {"base":"xs:positiveInteger","total":4},
  "tgPagCheq.dBcoEmi": {"base":"xs:string","minLen":4,"maxLen":20},
  "tgRasMerc.dNumLote": {"base":"noEmptyString","maxLen":80,"pat":[".+"]},
  "tgRasMerc.dNSerie": {"base":"noEmptyString","minLen":1,"maxLen":10},
  "tgRasMerc.dNumPedi": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgRasMerc.dNumSegui": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgVehNuevo.dColor": {"base":"noEmptyString","minLen":1,"maxLen":10},
  "tgVehNuevo.dPotencia": {"base":"xs:positiveInteger","total":4},
  "tgVehNuevo.dCapMot": {"base":"xs:positiveInteger","total":4},
  "tgVehNuevo.dNroMotor": {"base":"noEmptyString","maxLen":21,"minLen":1},
  "tgVehNuevo.dAnoFab": {"base":"xs:positiveInteger","pat":["[1-9][0-9]{3}"]},
  "tgVehNuevo.dCapac": {"base":"xs:positiveInteger","total":3},
  "tgVehNuevo.dCilin": {"base":"xs:string","pat":["/d"]},
  "tgGrupEner.dNroMed": {"base":"noEmptyString","minLen":1,"maxLen":50},
  "tgGrupEner.dActiv": {"base":"xs:integer","total":2},
  "tgGrupEner.dCateg": {"base":"noEmptyString","maxLen":3},
  "tgGrupSup.dNomCaj": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgGrupSup.dDesDonac": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgGrupSeg.dCodEmpSeg": {"base":"noEmptyString","maxLen":20},
  "tgGrupPolSeg.dUnidVig": {"base":"noEmptyString","minLen":3,"maxLen":15},
  "tgGrupPolSeg.dNumPoliza": {"base":"noEmptyString","maxLen":25},
  "tgGrupPolSeg.dCodInt": {"base":"noEmptyString","minLen":1,"maxLen":50},
  "tgGrupAdi.dCiclo": {"base":"noEmptyString","minLen":1,"maxLen":15},
  "tgGrupAdi.dContrato": {"base":"noEmptyString","minLen":1,"maxLen":30},
  "tgGrupAdi.dCodConDncp": {"base":"noEmptyString","minLen":1,"maxLen":30},
  "tgCamItem.dDesProSer": {"base":"noEmptyString","minLen":1,"maxLen":2000},
  "tgCamItem.dInfItem": {"base":"noEmptyString","minLen":1,"maxLen":500},
  "tgCamItem.dCanQuiMer": {"base":"xs:decimal","total":14,"frac":4,"minInc":0,"maxInc":9999999999.9999},
  "tgCamTrans.dDomFisc": {"base":"noEmptyString","maxLen":150,"minLen":1},
  "tgCamNRE.dKmR": {"base":"xs:integer","minInc":1,"maxInc":99999},
  "tgTransp.dNuManif": {"base":"noEmptyString","minLen":1,"maxLen":15},
  "tgTransp.dNuDespImp": {"base":"noEmptyString","len":16},
  "tgVehTras.dTiVehTras": {"base":"noEmptyString","minLen":4,"maxLen":10},
  "tgVehTras.dMarVeh": {"base":"noEmptyString","minLen":1,"maxLen":10},
  "tgVehTras.dTipIdenVeh": {"base":"xs:integer","pat":["[1-2]"]},
  "tgVehTras.dNroIDVeh": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgVehTras.dAdicVeh": {"base":"noEmptyString","minLen":1,"maxLen":20},
  "tgVehTras.dNroMatVeh": {"base":"noEmptyString","maxLen":7},
  "tgVehTras.dNroVuelo": {"base":"noEmptyString","len":6},
  "tgPagCred.iCondCred": {"base":"xs:positiveInteger","total":1,"enum":["1","2"]},
  "tgPagCred.dPlazoCre": {"base":"xs:string","minLen":2,"maxLen":15},
  "tgPagCred.dCuotas": {"base":"xs:positiveInteger","total":3},
  "tgCamFEI.dPuLleg": {"base":"noEmptyString","minLen":5,"maxLen":50},
  "tgCamFEI.dNuDesp": {"base":"noEmptyString","maxLen":16},
  "tgCamFEI.dNomDesp": {"base":"noEmptyString","maxLen":60,"minLen":4},
  "tgCamFEI.dVend": {"base":"noEmptyString","maxLen":30,"minLen":4},
  "tgCamFEI.dValorInv": {"base":"xs:decimal","total":12,"frac":4},
  "tgCamFEI.dValorFle": {"base":"xs:decimal","total":10,"frac":4},
  "tgCamFEI.dValorSeg": {"base":"xs:decimal","total":10,"frac":4,"minExc":0,"maxInc":9999999999},
  "tgCamFEI.dValorImpGs": {"base":"xs:integer","minExc":0,"maxInc":9999999999},
  "tgCamFEI.dDerAdu": {"base":"xs:decimal","total":12,"frac":4,"minExc":0,"maxInc":99999999.9999},
  "tgCamFEI.dIndi": {"base":"xs:decimal","total":12,"frac":4,"minExc":0,"maxInc":99999999.9999},
  "tgCamFEI.dSerValor": {"base":"xs:decimal","total":12,"frac":4,"minExc":0,"maxInc":99999999.9999},
  "tgCamFEI.dIVAImp": {"base":"xs:decimal","total":12,"frac":4,"minExc":0,"maxInc":99999999.9999},
  "tgCamFEI.dTasaIntAd": {"base":"xs:integer","minInc":1,"maxInc":99},
  "tgCamFEE.dPuEmb": {"base":"noEmptyString","minLen":5,"maxLen":30},
  "tDE.dSisFact": {"base":"xs:positiveInteger","maxInc":1},
  "tgCamDEAsoc.dNumComRet": {"base":"noEmptyString","len":15},
  "tgCamDEAsoc.dNumResCF": {"base":"noEmptyString","len":15},
  "tgCamDEAsoc.dNumCons": {"base":"xs:positiveInteger","pat":["[0-9]{11}"]},
  "tgCamDEAsoc.dNumControl": {"base":"noEmptyString","pat":["[0-9A-Za-z\\-]{8}"]},
  "tgCamGen.dOrdCompra": {"base":"noEmptyString","minLen":1,"maxLen":15},
  "tgCamGen.dOrdVta": {"base":"noEmptyString","minLen":1,"maxLen":15},
  "tgCamGen.dAsiento": {"base":"noEmptyString","minLen":1,"maxLen":10},
  "tgCamCarg.dTotVolMerc": {"base":"xs:positiveInteger","total":20},
  "tgCamCarg.dTotPesMerc": {"base":"xs:positiveInteger","total":20},
  "tgCamCarg.iCarCarga": {"base":"xs:positiveInteger","enum":["1","2","3"]},
  "tgCamCarg.dDesCarCarga": {"union":[{"base":"xs:string","enum":["Mercaderías con cadena de frío","Carga peligrosa"]},{"base":"noEmptyString","minLen":1,"maxLen":50,"pat":[".+"]}]},
  "tgCamFuFD.dCarQR": {"base":"noEmptyString","minLen":100,"maxLen":600},
  "tgCamFuFD.dInfAdic": {"base":"noEmptyString","minLen":1,"maxLen":5000},
  "rDE.dVerFor": {"base":"xs:integer","pat":["[1][5][0]"]},
  "tgCamRDE.dNumTrans": {"base":"noEmptyString","minLen":3,"maxLen":10},
  "tgCamRDE.dConc": {"base":"noEmptyString","minLen":1,"maxLen":255},
  "tgCamRDE.dNomEntFin": {"base":"noEmptyString","minLen":4,"maxLen":255},
  "tEmail": {"base":"xs:string","pat":["([0-9a-zA-Z]([0-9a-zA-Z\\.\\-_])*@([0-9a-zA-Z][0-9a-zA-Z\\-_]*\\.)+[a-zA-Z]{2,9})"]},
  "tDesPais": {"base":"noEmptyString","minLen":4,"maxLen":50},
  "tCDC": {"base":"xs:string","len":44,"pat":["[0-9]{2}([0-9]{7}[0-9A-D])[0-9]{34}"]},
  "tiTipEmi": {"base":"xs:positiveInteger","pat":["[1-2]"]},
  "tdDesTipEmi": {"base":"xs:string","minLen":6,"maxLen":12,"enum":["Normal","Contingencia"]},
  "tiCodSe": {"base":"xs:integer","minInc":1,"pat":["[0-9]{9}"]},
  "tiIndPres": {"base":"xs:integer","pat":["[1-6]|9"]},
  "tdDesIndPres": {"union":[{"base":"xs:string","enum":["Operación presencial","Operación electrónica","Operación telemarketing","Venta a domicilio","Operación bancaria","Operación cíclica"]},{"base":"noEmptyString","minLen":10,"maxLen":30,"pat":[".+"]}]},
  "tiTipTra": {"base":"xs:integer","minInc":1,"maxInc":13},
  "tdDesTiTran": {"base":"xs:string","enum":["Venta de mercadería","Prestación de servicios","Mixto (Venta de mercadería y servicios)","Venta de activo fijo","Venta de divisas","Compra de divisas","Promoción o entrega de muestras","Donación","Anticipo","Compra de productos","Compra de servicios","Venta de crédito fiscal","Muestras médicas (Art. 3 RG 24/2014)"]},
  "tdInfoEmi": {"base":"noEmptyString","maxLen":3000,"pat":[".+"]},
  "tdInfoFisc": {"base":"noEmptyString","maxLen":3000,"pat":[".+"]},
  "tiTiDE": {"base":"xs:integer","pat":["1|[4-7]|9|10"]},
  "tdDesTiDE": {"base":"xs:string","enum":["Factura electrónica","Autofactura electrónica","Nota de crédito electrónica","Nota de débito electrónica","Nota de remisión electrónica","Boleta de venta electrónica","Boleta resimple electrónica"]},
  "tdNumTim": {"union":[{"base":"xs:string","minLen":8,"maxLen":8,"pat":["0+[1-9][0-9]*|[1-9]+[0-9]+"]}]},
  "tdEst": {"base":"xs:string","minLen":3,"pat":["[0-9]{3}"]},
  "tdPunExp": {"base":"xs:string","minLen":3,"pat":["[0-9]{3}"]},
  "tdNumDoc": {"base":"xs:string","minLen":7,"maxLen":7,"pat":["0+[1-9][0-9]*|[1-9]+[0-9]+"]},
  "tdSerieNum": {"base":"noEmptyString","pat":["[A-Z]{2}"]},
  "tdNumDocId": {"base":"xs:string","pat":["[0-9A-Za-z\\-]{1,20}"]},
  "dNomRazSocial": {"base":"noEmptyString","maxLen":60,"minLen":4},
  "tdFeIniT": {"base":"xs:date","minInc":"2018-05-01","pat":["[2-9][0-9]{3}-([0][1-9]|[1][0-2])-([0][0-9]|[1-2][0-9]|[3][0-1])"]},
  "tdFeIniS": {"base":"xs:date","minInc":"2018-05-01"},
  "fecHhmmss": {"base":"xs:dateTime","pat":["\\d{4}-\\d\\d-\\d\\dT\\d\\d:\\d\\d:\\d\\d"]},
  "tiTImp": {"base":"xs:integer","enum":["1","2","3","4","5"]},
  "tdDesTImp": {"base":"xs:string","enum":["IVA","ISC","Renta","Ninguno","IVA - Renta"]},
  "tRuc": {"base":"xs:string","minLen":3,"maxLen":8,"pat":["[1-9][0-9]*[0-9A-D]?"]},
  "tDVer": {"base":"xs:integer","pat":["[0-9]"]},
  "tiTipCont": {"base":"xs:integer","pat":["[1-2]"]},
  "tcTipReg": {"base":"xs:integer","pat":["[1-8]"]},
  "tcTipRegAdu": {"base":"xs:integer","pat":["[0-9]{4}"]},
  "tcCiuEmi": {"base":"xs:integer","minInc":1,"maxInc":99999,"pat":["[0-9]{1,5}"]},
  "tdDesCiuEmi": {"base":"noEmptyString","minLen":1,"maxLen":30},
  "tcDisEmi": {"base":"xs:integer","minInc":1,"pat":["[0-9]{1,4}"]},
  "tdDesDisEmi": {"base":"noEmptyString","minLen":1,"maxLen":30},
  "tdTel": {"base":"xs:string","minLen":6,"maxLen":15,"pat":[".+"]},
  "tdCel": {"base":"xs:string","minLen":10,"maxLen":20,"pat":[".+"]},
  "tcActEco": {"base":"xs:string","minLen":1,"maxLen":8,"pat":["[0-9A-Z]{1,8}"]},
  "tdDesActEco": {"base":"noEmptyString","minLen":1,"maxLen":300},
  "tcOblAfe": {"base":"xs:integer","total":3,"pat":["[1-9][0-9][0-9]"]},
  "tdDesOblAfe": {"base":"noEmptyString","minLen":21,"maxLen":65},
  "tiNatRec": {"base":"xs:integer","pat":["[1-2]"]},
  "tiNatVen": {"base":"xs:integer","pat":["[1-2]"]},
  "tdDesNatVen": {"base":"xs:string","minLen":10,"maxLen":16,"enum":["No contribuyente","Extranjero"]},
  "tiTiOpe": {"base":"xs:integer","pat":["[1-4]"]},
  "tiTipDoc": {"base":"xs:integer","pat":["[1-4]"]},
  "tiTipDocRec": {"base":"xs:integer","pat":["[1-6]|9"]},
  "tiTipIDRespDE": {"base":"xs:integer","pat":["[1-4]|9"]},
  "tdDtipDoc": {"base":"xs:string","enum":["Cédula paraguaya","Pasaporte","Cédula extranjera","Carnet de residencia"]},
  "tdDtipDocRec": {"union":[{"base":"xs:string","enum":["Cédula paraguaya","Pasaporte","Cédula extranjera","Carnet de residencia","Innominado","Tarjeta Diplomática de exoneración fiscal"]},{"base":"noEmptyString","minLen":9,"maxLen":41,"pat":[".+"]}]},
  "tdDTipIDRespDE": {"union":[{"base":"xs:string","enum":["Cédula paraguaya","Pasaporte","Cédula extranjera","Carnet de residencia"]},{"base":"noEmptyString","minLen":9,"maxLen":41,"pat":[".+"]}]},
  "tiCondOpe": {"base":"xs:integer","enum":["1","2"],"pat":["[1-2]"]},
  "tdDCondOpe": {"base":"xs:string","enum":["Contado","Crédito"]},
  "tiTiPago": {"base":"xs:integer","total":2,"enum":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","99"]},
  "tdDesTiPag": {"union":[{"base":"xs:string","enum":["Efectivo","Cheque","Tarjeta de crédito","Tarjeta de débito","Transferencia","Giro","Billetera electrónica","Tarjeta empresarial","Vale","Retención","Pago por anticipo","Valor fiscal","Valor comercial","Compensación","Permuta","Pago bancario","Pago Móvil","Donación","Promoción","Consumo Interno","Pago Electrónico"]},{"base":"noEmptyString","minLen":4,"maxLen":30,"pat":[".+"]}]},
  "tdDMoneTiPag": {"base":"noEmptyString","minLen":3,"maxLen":20},
  "tiDenTarj": {"base":"xs:integer","total":2,"enum":["1","2","3","4","5","6","99"]},
  "tdDesDenTarj": {"union":[{"base":"xs:string","minLen":4,"maxLen":20,"enum":["Visa","Mastercard","American Express","Maestro","Panal","Cabal"]},{"base":"noEmptyString","minLen":4,"maxLen":20,"pat":[".+"]}]},
  "tiForProPa": {"base":"xs:short","total":1,"enum":["1","2","9"]},
  "tdNunApOpe": {"base":"xs:positiveInteger","total":10,"minInc":100000},
  "tNumCheq": {"base":"xs:string","minLen":8,"maxLen":8,"pat":["[0-9]{8}"]},
  "tdDCondCred": {"base":"xs:string","enum":["Plazo","Cuota"]},
  "tFecAAAAMMDD": {"base":"xs:string","pat":["[2-9][0-9]{3}([0][1-9]|[1][0-2])([0][0-9]|[1-2][0-9]|[3][0-1])"]},
  "tFecAAAAMMDDguion": {"base":"xs:string","pat":["[2-9][0-9]{3}-([0][1-9]|[1][0-2])-([0][0-9]|[1-2][0-9]|[3][0-1])"]},
  "tFecDocImpAAAAMMDDguion": {"base":"xs:string","pat":["[2-9][0-9]{3}-([0][1-9]|[1][0-2])-([0][0-9]|[1-2][0-9]|[3][0-1])"]},
  "tFecDDMMAAAAguion": {"base":"xs:string","pat":["([0][0-9]|[1-2][0-9]|[3][0-1])-([0][1-9]|[1][0-2])-[1-9][0-9]{3}"]},
  "tdModCont": {"base":"noEmptyString","len":2},
  "tdEntCont": {"base":"xs:positiveInteger","minInc":1,"pat":["[0-9]{5}"]},
  "tdAnoCont": {"base":"xs:positiveInteger","total":2},
  "tdSecCont": {"base":"xs:positiveInteger","minInc":1,"pat":["[0-9]{7}"]},
  "tdCondTiCam": {"base":"xs:short","total":1,"enum":["1","2"]},
  "tiCondAnt": {"base":"xs:short","total":1,"enum":["1","2"]},
  "tdDesCondAnt": {"base":"xs:string","enum":["Anticipo Global","Anticipo por Ítem"]},
  "tdCodInt": {"base":"noEmptyString","minLen":1,"maxLen":50},
  "tdParAranc": {"base":"xs:positiveInteger","pat":["[0-9]{4}"]},
  "tdNCM": {"base":"xs:positiveInteger","pat":["[0-9]{6,8}"]},
  "tdDncpG": {"base":"xs:string","pat":["[0-9]{8}"]},
  "tdDncpE": {"base":"xs:string","pat":["[0-9]{3,4}"]},
  "tdGtin": {"base":"xs:positiveInteger","pat":["[0-9]{8,14}"]},
  "tdCantProSer": {"base":"xs:decimal","total":18,"frac":8,"minInc":0,"maxInc":10000000000},
  "tcRelMerc": {"base":"xs:integer","pat":["[1-2]"]},
  "tdDesRelMerc": {"base":"xs:string","minLen":19,"maxLen":21,"enum":["Tolerancia de quiebra","Tolerancia de merma"]},
  "tMontoBase": {"base":"xs:decimal","total":23,"frac":8,"minInc":0,"maxInc":1E+15},
  "tMontoBase4": {"base":"xs:decimal","total":19,"frac":4,"minInc":0,"maxInc":1E+15},
  "tMontoBase6": {"base":"xs:decimal","total":10,"frac":4,"minInc":0,"maxInc":999999.9999},
  "tTipoCambioBase": {"base":"xs:decimal","total":9,"frac":4,"minExc":0,"maxExc":99999.9999},
  "tPorcDesc8": {"base":"xs:decimal","total":11,"frac":8,"minInc":0,"maxInc":100},
  "tiAfecIVA": {"base":"xs:positiveInteger","enum":["1","2","3","4"]},
  "tdDesAfecIVA": {"base":"xs:string","enum":["Gravado IVA","Exonerado (Art. 100 - Ley 6380/2019)","Exento","Gravado parcial (Grav- Exento)"]},
  "tdTasaIVA": {"base":"xs:integer","total":2,"minInc":0},
  "tcCatISC": {"base":"xs:integer","enum":["1","2","3","4","5"]},
  "tdDesCatISC": {"base":"xs:string","enum":["SECCION I-(Cigarrillos,Tabacos,Esencias y Otros derivados del Tabaco)","SECCION II - (Bebidas con y sin alcohol)","SECCION III - (Alcoholes y Derivados del alcohol)","SECCION IV - (Combustibles)","SECCION V - (Artículos considerados de lujo)"]},
  "tcTasaISC": {"base":"xs:integer","enum":["1","2","3","4","5","6","7","8","9","10","11","12"]},
  "tiTipOpVN": {"base":"xs:short","enum":["1","2","3","4"]},
  "tdDesTipOpVN": {"union":[{"base":"xs:string","enum":["Venta a representante","Venta al Consumidor final","Venta a gobierno","Venta a flota de vehículos"]}]},
  "tdChasis": {"base":"xs:string","pat":["[0-9A-Za-z]{17}"]},
  "tiTipCom": {"base":"xs:integer","enum":["1","2","3","4","5","9"]},
  "tdDesTipCom": {"union":[{"base":"xs:string","enum":["Gasolina","Diésel","Etanol","GNV","Flex"]},{"base":"noEmptyString","minLen":3,"maxLen":20,"pat":[".+"]}]},
  "tiTipoPint": {"base":"xs:positiveInteger","enum":["1","2","3","4","9"]},
  "tdDesTP": {"union":[{"base":"xs:string","enum":["Solida","Metalica","Perla","Fosca"]},{"base":"xs:string","minLen":4,"maxLen":10,"pat":["[A-Za-z0-9]"]}]},
  "tcTipVeh": {"base":"noEmptyString","minLen":4,"maxLen":10},
  "tiCondVeh": {"base":"xs:short","enum":["1","2","3"]},
  "tdDesCondVeh": {"base":"xs:string","enum":["Acabado","Semi-acabado","Inacabado"]},
  "tLectura": {"base":"xs:decimal","total":13,"frac":2,"minInc":0,"maxInc":99999999999.99},
  "tdPoliza": {"base":"noEmptyString","maxLen":20},
  "tdVigPol": {"base":"xs:decimal","total":6,"frac":1,"minExc":0,"maxInc":99999.9},
  "tdCRed": {"base":"xs:decimal","total":8,"frac":4,"minInc":0,"maxInc":9999.9999},
  "noEmptyString": {"base":"xs:string","minLen":1,"pat":[".*[^\\s].*"]},
  "tdTipCons": {"base":"xs:positiveInteger","enum":["1","2"]},
  "tdDesTipCons": {"base":"xs:string","enum":["Constancia de no ser contribuyente","Constancia de microproductores"]},
  "tCiudad": {"base":"xs:positiveInteger","total":5},
  "tDesCiudad": {"base":"noEmptyString","maxLen":30},
  "tDistrito": {"base":"xs:positiveInteger","total":4},
  "tDesDistrito": {"base":"noEmptyString","minLen":1,"maxLen":30},
  "tiTipDocAso": {"base":"xs:integer","enum":["1","2","3"]},
  "tdDesTipDocAso": {"base":"xs:string","enum":["Electrónico","Impreso","Constancia Electrónica"]},
  "tiTIpoDoc": {"base":"xs:positiveInteger","enum":["1","2","3","4"]},
  "tdDesTIpoDoc": {"base":"xs:string","enum":["Factura","Nota de crédito","Nota de débito","Nota de remisión"]},
  "tiMotEmi": {"base":"noEmptyString","pat":["[1-8]"]},
  "tdDesMotEmi": {"base":"xs:string","enum":["Devolución y Ajuste de precios","Devolución","Descuento","Bonificación","Crédito incobrable","Recupero de costo","Recupero de gasto","Ajuste de precio"]},
  "tiMotivTras": {"base":"xs:integer","enum":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","99"]},
  "tdDMotivTras": {"union":[{"base":"xs:string","enum":["Traslado por ventas","Traslado por consignación","Exportación","Traslado por compra","Importación","Traslado por devolución","Traslado entre locales de la empresa","Traslado de bienes por transformación","Traslado de bienes para reparación","Traslado por emisor móvil","Exhibición o Demostración","Participación en ferias","Traslado de encomienda","Decomiso"]},{"base":"noEmptyString","maxLen":60,"minLen":5}]},
  "tiRespEmiNR": {"base":"xs:integer","enum":["1","2","3","4","5"]},
  "tdDesRespEmiNR": {"union":[{"base":"xs:string","minLen":20,"maxLen":36,"enum":["Emisor de la factura","Poseedor de la factura y bienes","Empresa transportista","Despachante de Aduanas","Agente de transporte o intermediario"]}]},
  "tiTTrans": {"base":"xs:integer","minInc":1,"enum":["1","2"]},
  "tdDesTTrans": {"base":"xs:string","enum":["Propio","Tercero"]},
  "tiModTrans": {"base":"xs:integer","enum":["1","2","3","4"]},
  "tdDesModTrans": {"base":"xs:string","enum":["Terrestre","Fluvial","Aéreo","Multimodal"]},
  "tiRespFlete": {"base":"xs:integer","enum":["1","2","3","4","5"]},
  "tcCondNeg": {"base":"xs:string","enum":["CFR","CIF","CIP","CPT","DAP","DAT","DDP","EXW","FAS","FCA","FOB"]},
  "tdDirec": {"base":"noEmptyString","maxLen":255},
  "tdNumCas": {"base":"xs:integer","minInc":0,"total":6},
  "tdDirec2": {"base":"noEmptyString","maxLen":15},
  "tdNombre": {"base":"noEmptyString","maxLen":255,"minLen":4},
  "tdCargo": {"base":"noEmptyString","maxLen":100,"minLen":4},
  "tdCadenaBase": {"base":"noEmptyString","maxLen":20,"minLen":20},
  "tdNomPro": {"base":"noEmptyString","maxLen":30,"minLen":1},
  "tdCadenaBase20": {"base":"noEmptyString","maxLen":20,"minLen":1},
  "tiForPag": {"base":"xs:integer","total":1,"enum":["1","2"]},
  "tdDesForPag": {"union":[{"base":"xs:string","enum":["Efectivo","Transferencia bancaria"]},{"base":"noEmptyString","minLen":8,"maxLen":22,"pat":[".+"]}]},
  "tcUniMed": {"base":"xs:integer","enum":["87","2366","2329","110","77","86","89","90","91","92","93","94","96","79","97","98","99","100","101","104","103","108","109","95","666","102","83","88","625","660","885","891","869","569","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140"]},
  "tdDesUniMed": {"base":"xs:string","minLen":1,"maxLen":10,"enum":["m","CPM","UI","M3","UNI","g","LT","MG","CM","CM2","CM3","PUL","MM2","kg/m2","AA","ME","TN","Hs","Mi","DET","Ya","MT","M2","MM","Se","Di","kg","ML","Km","ml","GL","pm","ha","ración","4A","Ci","DOC","GLL","GRO","E4","KT","M5","MCU","MIL","PAR","FOT","FTK","PCE","KLT","RM","RO","kWh","U(JGO)","DR","BX","SET","PK","BG","DPC","JR","BL","AB","BK","BW"]},
  "paisType": {"base":"xs:string","enum":["MKD","TWN","DZA","EGY","LBY","MAR","SDN","TUN","ESH","IOT","BDI","COM","DJI","ERI","ETH","ATF","KEN","MDG","MWI","MUS","MYT","MOZ","REU","RWA","SYC","SOM","SSD","UGA","TZA","ZMB","ZWE","AGO","CMR","CAF","TCD","COG","COD","GNQ","GAB","STP","BWA","LSO","NAM","ZAF","SWZ","BEN","BFA","CPV","CIV","GMB","GHA","GIN","GNB","LBR","MLI","MRT","NER","NGA","SHN","SEN","SLE","TGO","AIA","ATG","ABW","BHS","BRB","BES","VGB","CYM","CUB","CUW","DMA","DOM","GRD","GLP","HTI","JAM","MTQ","MSR","PRI","BLM","KNA","LCA","MAF","VCT","SXM","TTO","TCA","VIR","BLZ","CRI","SLV","GTM","HND","MEX","NIC","PAN","ARG","BOL","BRA","CHL","COL","ECU","FLK","GUF","GUY","PRY","PER","SGS","SUR","URY","VEN","BMU","CAN","GRL","SPM","USA","ATA","KAZ","KGZ","TJK","TKM","UZB","CHN","HKG","MAC","PRK","JPN","MNG","KOR","BRN","KHM","IDN","LAO","MYS","MMR","PHL","SGP","THA","TLS","VNM","AFG","BGD","BTN","IND","IRN","MDV","NPL","PAK","LKA","ARM","AZE","BHR","CYP","GEO","IRQ","ISR","JOR","KWT","LBN","OMN","QAT","SAU","PSE","SYR","TUR","ARE","YEM","BLR","BGR","CZE","HUN","POL","MDA","ROU","RUS","SVK","UKR","ALA","GGY","JEY","DNK","EST","FRO","FIN","ISL","IRL","IMN","LVA","LTU","NOR","SJM","SWE","GBR","ALB","AND","BIH","HRV","GIB","GRC","VAT","ITA","MLT","MNE","PRT","SMR","SRB","SVN","ESP","MKD","AUT","BEL","FRA","DEU","LIE","LUX","MCO","NLD","CHE","AUS","CXR","CCK","HMD","NZL","NFK","FJI","NCL","PNG","SLB","VUT","GUM","KIR","MHL","FSM","NRU","MNP","PLW","UMI","ASM","COK","PYF","NIU","PCN","WSM","TKL","TON","TUV","WLF","NN"]},
  "tDepartamentos": {"base":"xs:integer","enum":["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20"]},
  "tDesDepartamento": {"base":"xs:string","enum":["CAPITAL","CONCEPCION","SAN PEDRO","CORDILLERA","GUAIRA","CAAGUAZU","CAAZAPA","ITAPUA","MISIONES","PARAGUARI","ALTO PARANA","CENTRAL","NEEMBUCU","AMAMBAY","PTE. HAYES","BOQUERON","ALTO PARAGUAY","CANINDEYU","CHACO","NUEVA ASUNCION"]},
  "cMondT": {"base":"xs:normalizedString","enum":["AED","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZM","BAM","BBD","BYN","BDT","BGN","BHD","BIF","BMD","BND","BOB","BOV","BRL","BSD","BTN","BWP","BYR","BZD","CAD","CDF","CHF","CHE","CHW","CLP","CLF","CNY","COP","COU","CRC","CUP","CUC","CVE","CYP","CZK","DJF","DKK","DOP","DZD","EEK","EGP","ERN","ETB","EUR","FJD","FKP","GBP","GEL","GHS","GHC","GIP","GMD","GNF","GTQ","GYD","HKD","HNL","HRK","HTG","HUF","IDR","ILS","INR","IQD","IRR","ISK","JMD","JOD","JPY","KES","KGS","KHR","KMF","KPW","KRW","KWD","KYD","KZT","LAK","LBP","LKR","LRD","LSL","LTL","LVL","LYD","MAD","MZN","MDL","MGF","MKD","MGA","MMK","MNT","MOP","MRO","MTL","MUR","XUA","MVR","MRU","MWK","MXN","MXV","MYR","MZM","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PGK","PHP","PKR","PLN","PYG","QAR","RON","ROL","RUB","RWF","SAR","RSD","SBD","SCR","SDD","SDG","SRD","SEK","SGD","SHP","SIT","SKK","SLL","SOS","SRG","SSP","STD","SVC","SYP","SZL","THB","TJS","TMM","TND","TRY","TMT","TOP","TRL","TTD","TWD","TZS","UAH","UGX","USD","USN","UYU","UYI","UYW","UZS","VEB","VND","VUV","VES","WST","STN","XAF","XAG","XAU","XCD","XDR","XOF","XPD","XPF","XPT","XSU","XBA","XBB","XBC","XTS","XXX","YER","YUM","ZMW","ZWL","ZAR","ZMK","ZWD"]},
};
